apiVersion: v1
kind: ReplicationController
metadata:
    name: rc1
spec:
  replicas: 3
  selector:
    run: po1
  template:
      metadata:
              name: nginx
              labels:
                run: po1
      spec:
          containers:
              - name: nginx
                image: nginx
                

